<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13213" started-at="2020-02-15T16:33:17 IST" finished-at="2020-02-15T16:33:30 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="13213" started-at="2020-02-15T16:33:17 IST" finished-at="2020-02-15T16:33:30 IST">
      <class name="com.home.test.testcases.SearchProduct">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.home.test.testcases.SearchProduct@345965f2]" name="setUp" is-config="true" duration-ms="9" started-at="2020-02-15T16:33:17 IST" finished-at="2020-02-15T16:33:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="initMethod()[pri:0, instance:com.home.test.testcases.SearchProduct@345965f2]" name="initMethod" is-config="true" duration-ms="9701" started-at="2020-02-15T16:33:17 IST" finished-at="2020-02-15T16:33:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMethod -->
        <test-method status="PASS" signature="searchProduct()[pri:0, instance:com.home.test.testcases.SearchProduct@345965f2]" name="searchProduct" duration-ms="1646" started-at="2020-02-15T16:33:27 IST" description="Search a product from Amazon." finished-at="2020-02-15T16:33:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProduct -->
        <test-method status="PASS" signature="initMethod()[pri:0, instance:com.home.test.testcases.SearchProduct@345965f2]" name="initMethod" is-config="true" duration-ms="1" started-at="2020-02-15T16:33:29 IST" finished-at="2020-02-15T16:33:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMethod -->
        <test-method status="FAIL" signature="searchProduct1()[pri:1, instance:com.home.test.testcases.SearchProduct@345965f2]" name="searchProduct1" duration-ms="1464" started-at="2020-02-15T16:33:29 IST" description="Login to Gmail." finished-at="2020-02-15T16:33:30 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.home.test.testcases.SearchProduct.searchProduct1(SearchProduct.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProduct1 -->
      </class> <!-- com.home.test.testcases.SearchProduct -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
